// Package fib provides the FIB manager for the XDP-based cached FIB lookup system.
package fib

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -cflags "-O2 -g -Wall -Werror -DCACHE_SIZE=65536" -target amd64,arm64 bpf ../../bpf/fib.c -- -I/usr/include

// Note: BPF struct types (bpfLpmKey, bpfFwdInfo, bpfCacheKey, bpfStats, bpfConfig)
// are auto-generated by bpf2go in bpf_*_bpfel.go files.
// Do NOT define manual types here - they won't match the generated types' memory layout.
